version: "3.8"

services:

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  airflow:
    build: .
    command: standalone
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      #AIRFLOW__CORE__FERNET_KEY: "REPLACE_WITH_REAL_KEY"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      AIRFLOW_CONN_MONGO_DEFAULT: "mongodb://admin:password@mongo:27017/"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  mongo_data:
